netty:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql:///snake
    username: root
#    password: 123456
    password: admin@yqiekOjgV8(;


logging:
  file:
    path: /var/log/snake
  level:
    root: info